### ISSUE TITLE
Link in Getting Started readme doesn't work

### ISSUE THREAD

**Issue by nrchaney** [IBM-Bluemix-Docs/document-conversion#7]
`To continue using features, you will need to (migrate)[/docs/services/discovery/migrate-dcs-rr.html].` should probably be `To continue using features, you will need to [migrate](/docs/services/discovery/migrate-dcs-rr.html).`

**Comment by SirSpidey** [comment]
Thanks. Fixed in https://github.com/IBM-Bluemix-Docs/document-conversion/pull/8
